engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  csslint:
    enabled: true

ratings:
  paths:
  - "**.js"

exclude_paths:
  - node_modules/**
  - public/**
  - test/**